XRDDEV-1507 allow upgrade in prerm

diff --git a/src/packages/src/xroad/ubuntu/generic/xroad-base.prerm b/src/packages/src/xroad/ubuntu/generic/xroad-base.prerm
--- a/src/packages/src/xroad/ubuntu/generic/xroad-base.prerm
+++ b/src/packages/src/xroad/ubuntu/generic/xroad-base.prerm
@@ -6,14 +6,14 @@ echo "prerm script executing"
 echo "Printing parameters"
 echo $@
 
-if [ "$1" = "upgrade" ]; then
-  echo "prerm script upgrade"
-  echo "this is where we check if the package upgrade is allowed"
-  exit 1
-elif [ "$1" = "failed-upgrade" ]; then
-  echo "prerm script failed-upgrade"
-  exit 1
-else
-  echo "no match for the parameter"
-  echo "$1"
-fi
+#if [ "$1" = "upgrade" ]; then
+#  echo "prerm script upgrade"
+#  echo "this is where we check if the package upgrade is allowed"
+#  exit 1
+#elif [ "$1" = "failed-upgrade" ]; then
+#  echo "prerm script failed-upgrade"
+#  exit 1
+#else
+#  echo "no match for the parameter"
+#  echo "$1"
+#fi
